# Generated by Django 5.2.3 on 2025-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='boleta_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletas/'),
        ),
    ]
