services:
  - type: web
    name: veterinario-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      # 1️⃣ Asegúrate de que Python “vea” tu repo como workspace
      export PYTHONPATH=$PWD &&

      # 2️⃣ Lanza Gunicorn apuntando a core.wsgi, con chdir y logs
      gunicorn core.wsgi:application \
        --chdir . \
        --workers 3 \
        --bind 0.0.0.0:10000 \
        --log-level info \
        --access-logfile - \
        --error-logfile -
    envVars:
      - key: DEBUG
        value: "False"
