services:
  - type: web
    name: veterinario-app
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: >
      gunicorn veterinario.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: veterinario.settings
      - key: PYTHONPATH
        value: /opt/render/project/src  # o la ruta exacta
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: veterinario-app.onrender.com
      - key: DATABASE_URL
        value: <tu URL de Postgres>
