services:
  - type: web
    name: veterinario-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn SLOOT123.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
